name: Directory writer
on: [push]
  #schedule:
  #        ┌───────────── minute (0 - 59)
  #        │  ┌───────────── hour (0 - 23)
  #        │  │ ┌───────────── day of the month (1 - 31)
  #        │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
  #        │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
  #        │  │ │ │ │
  #        │  │ │ │ │
  #        │  │ │ │ │
  #        *  * * * *
  #- cron: '0 0 * * *'
  #workflow_dispatch:
jobs:
  build:
    # if: github.repository == 'TheAlgorithms/Julia' # We only need this to run in our repository.
    #runs-on: ubuntu-latest
    #steps:
    #  - uses: actions/checkout@v4
    #    with:
    #      fetch-depth: 0
    #  - name: Build directory
    #    uses: TheAlgorithms/scripts/directory_md@main
    #    with:
    #      language: Julia
    #      working-directory: src
    #      filetypes: jl
    #      ignored-directories: docs/,pluto_notebooks/,test/
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Julia v1.8
        uses: julia-actions/setup-julia@v1
        with:
          version: 1.8
      - name: Build DIRECTORY.md
        run: julia scripts/directory_writer.jl
      - name: Update DIRECTORY.md
        run: |
          git add DIRECTORY.md
          git commit -am "updating DIRECTORY.md" ||  true
          git push --force origin HEAD:$GITHUB_REF || true
